apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tsz-local-rate-limit
  namespace: tsz-byg-demo
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: mock-openai
  rateLimit:
    local:
      rules:
        - limit:
            requests: 2
            unit: Minute
