---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsz-controller
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.envoyproxy.io
  resources:
  - envoyextensionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - grpcroutes
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.thyris.ai
  resources:
  - tszguardrailpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.thyris.ai
  resources:
  - tszguardrailpolicies/status
  verbs:
  - get
  - patch
  - update
