//go:build !ignore_autogenerated

// Copyright {{ .Year }} ThyrisAI.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientOverridesSpec) DeepCopyInto(out *ClientOverridesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientOverridesSpec.
func (in *ClientOverridesSpec) DeepCopy() *ClientOverridesSpec {
	if in == nil {
		return nil
	}
	out := new(ClientOverridesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailurePolicySpec) DeepCopyInto(out *FailurePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailurePolicySpec.
func (in *FailurePolicySpec) DeepCopy() *FailurePolicySpec {
	if in == nil {
		return nil
	}
	out := new(FailurePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestPolicySpec) DeepCopyInto(out *RequestPolicySpec) {
	*out = *in
	if in.CustomPatternIDs != nil {
		in, out := &in.CustomPatternIDs, &out.CustomPatternIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowlistIDs != nil {
		in, out := &in.AllowlistIDs, &out.AllowlistIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlocklistIDs != nil {
		in, out := &in.BlocklistIDs, &out.BlocklistIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomValidators != nil {
		in, out := &in.CustomValidators, &out.CustomValidators
		*out = make([]ValidatorReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestPolicySpec.
func (in *RequestPolicySpec) DeepCopy() *RequestPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RequestPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponsePolicySpec) DeepCopyInto(out *ResponsePolicySpec) {
	*out = *in
	if in.CustomPatternIDs != nil {
		in, out := &in.CustomPatternIDs, &out.CustomPatternIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomValidators != nil {
		in, out := &in.CustomValidators, &out.CustomValidators
		*out = make([]ValidatorReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponsePolicySpec.
func (in *ResponsePolicySpec) DeepCopy() *ResponsePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ResponsePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingSpec) DeepCopyInto(out *StreamingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingSpec.
func (in *StreamingSpec) DeepCopy() *StreamingSpec {
	if in == nil {
		return nil
	}
	out := new(StreamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSZGuardrailPolicy) DeepCopyInto(out *TSZGuardrailPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSZGuardrailPolicy.
func (in *TSZGuardrailPolicy) DeepCopy() *TSZGuardrailPolicy {
	if in == nil {
		return nil
	}
	out := new(TSZGuardrailPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TSZGuardrailPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSZGuardrailPolicyList) DeepCopyInto(out *TSZGuardrailPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TSZGuardrailPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSZGuardrailPolicyList.
func (in *TSZGuardrailPolicyList) DeepCopy() *TSZGuardrailPolicyList {
	if in == nil {
		return nil
	}
	out := new(TSZGuardrailPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TSZGuardrailPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSZGuardrailPolicySpec) DeepCopyInto(out *TSZGuardrailPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1alpha2.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(RequestPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(ResponsePolicySpec)
		(*in).DeepCopyInto(*out)
	}
	out.FailurePolicy = in.FailurePolicy
	if in.ProcessingTimeout != nil {
		in, out := &in.ProcessingTimeout, &out.ProcessingTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Streaming != nil {
		in, out := &in.Streaming, &out.Streaming
		*out = new(StreamingSpec)
		**out = **in
	}
	out.ClientOverrides = in.ClientOverrides
	out.Telemetry = in.Telemetry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSZGuardrailPolicySpec.
func (in *TSZGuardrailPolicySpec) DeepCopy() *TSZGuardrailPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TSZGuardrailPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSZGuardrailPolicyStatus) DeepCopyInto(out *TSZGuardrailPolicyStatus) {
	*out = *in
	if in.PolicyVersion != nil {
		in, out := &in.PolicyVersion, &out.PolicyVersion
		*out = new(int)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetRefStatuses != nil {
		in, out := &in.TargetRefStatuses, &out.TargetRefStatuses
		*out = make([]TargetRefStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSZGuardrailPolicyStatus.
func (in *TSZGuardrailPolicyStatus) DeepCopy() *TSZGuardrailPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TSZGuardrailPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRefStatus) DeepCopyInto(out *TargetRefStatus) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRefStatus.
func (in *TargetRefStatus) DeepCopy() *TargetRefStatus {
	if in == nil {
		return nil
	}
	out := new(TargetRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorReference) DeepCopyInto(out *ValidatorReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorReference.
func (in *ValidatorReference) DeepCopy() *ValidatorReference {
	if in == nil {
		return nil
	}
	out := new(ValidatorReference)
	in.DeepCopyInto(out)
	return out
}
